import { ReceiptData } from '../api/receipts';

export const generateReceiptsHTML = (receipts: ReceiptData[], title: string): string => {
    const date = new Date().toLocaleDateString();

    const tableRows = receipts.map(receipt => {
        const formattedDate = receipt.date || 'N/A';
        const formattedTotal = typeof receipt.total === 'number'
            ? `₹${receipt.total.toFixed(2)}`
            : receipt.total;
        const storeName = receipt.store_name || 'Unknown Store';
        const category = receipt.category || 'Uncategorized';

        return `
            <tr>
                <td>${formattedDate}</td>
                <td>${storeName}</td>
                <td>${category}</td>
                <td class="amount">${formattedTotal}</td>
            </tr>
        `;
    }).join('');

    const totalAmount = receipts.reduce((sum, receipt) => {
        let amount = 0;
        if (typeof receipt.total === 'number') {
            amount = receipt.total;
        } else if (typeof receipt.total === 'string') {
            const numericTotal = parseFloat(receipt.total.replace(/,/g, ''));
            if (!isNaN(numericTotal)) {
                amount = numericTotal;
            }
        }
        return sum + amount;
    }, 0);

    return `
        <!DOCTYPE html>
        <html>
        <head>
            <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no" />
            <style>
                body {
                    font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
                    color: #333;
                    padding: 40px;
                }
                .header {
                    text-align: center;
                    margin-bottom: 40px;
                }
                .header h1 {
                    color: #4f46e5;
                    margin-bottom: 10px;
                }
                .header p {
                    color: #666;
                    font-size: 14px;
                }
                table {
                    width: 100%;
                    border-collapse: collapse;
                    margin-bottom: 30px;
                }
                th {
                    background-color: #f3f4f6;
                    color: #374151;
                    font-weight: 600;
                    text-align: left;
                    padding: 12px;
                    border-bottom: 2px solid #e5e7eb;
                }
                td {
                    padding: 12px;
                    border-bottom: 1px solid #e5e7eb;
                    color: #4b5563;
                }
                .amount {
                    text-align: right;
                    font-family: 'Courier New', Courier, monospace;
                    font-weight: 600;
                }
                th:last-child {
                    text-align: right;
                }
                .summary {
                    text-align: right;
                    margin-top: 20px;
                    font-size: 18px;
                    font-weight: bold;
                    color: #111827;
                }
                .footer {
                    margin-top: 50px;
                    text-align: center;
                    font-size: 12px;
                    color: #9ca3af;
                    border-top: 1px solid #e5e7eb;
                    padding-top: 20px;
                }
            </style>
        </head>
        <body>
            <div class="header">
                <h1>${title}</h1>
                <p>Generated on ${date}</p>
            </div>
            
            <table>
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>Store</th>
                        <th>Category</th>
                        <th>Amount</th>
                    </tr>
                </thead>
                <tbody>
                    ${tableRows}
                </tbody>
            </table>
            
            <div class="summary">
                Total: ₹${totalAmount.toFixed(2)}
            </div>
            
            <div class="footer">
                <p>Generated by Bill Extractor App</p>
            </div>
        </body>
        </html>
    `;
};
